version: '2'
services:
    togglzexample-app:
        image: togglzexample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://togglzexample-postgresql:5432/togglzexample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    togglzexample-postgresql:
        extends:
            file: postgresql.yml
            service: togglzexample-postgresql
